### ISSUE TITLE
release 3.2.0 declares dependency on  psycopg-binary==3.2.0.dev1 and psycopg-c==3.2.0.dev1, which are not available on pypa

### ISSUE THREAD

**Issue by jizhilong** [psycopg/psycopg#855] opened 2024-07-01 03:05 UTC
Dear psycopg maintainer,
   The metadata file  of the [new release](https://pypi.org/project/psycopg/3.2.0/) declares depdency on pycopg-binary==3.2.0.dev1 and pyscopg-c==3.2.0.dev1:
    
![image](https://github.com/psycopg/psycopg/assets/816618/83b5d965-2433-468b-a8b2-1f483090154a)
    
   While according to [pyscopg-binary release history](https://pypi.org/project/psycopg-binary/#history), it  has no release with version 3.2.0.dev1, so is pyscopg-c.

   So the installation of psycopg will break on most platforms with errors like following:

```
ERROR: Could not find a version that satisfies the requirement psycopg-binary==3.2.0.dev1; implementation_name != "pypy" and extra == "binary" (from psycopg[binary]<4.0.0,>=3.1.10->mig25) (from versions: 3.0.15, 3.0.16, 3.0.17, 3.0.18, 3.1, 3.1.1, 3.1.2, 3.1.3, 3.1.4, 3.1.5, 3.1.6, 3.1.8, 3.1.9, 3.1.10, 3.1.11, 3.1.12, 3.1.13, 3.1.14, 3.1.15, 3.1.16, 3.1.17, 3.1.18, 3.1.19, 3.1.20, 3.2.0)
ERROR: No matching distribution found for psycopg-binary==3.2.0.dev1; implementation_name != "pypy" and extra == "binary" (from psycopg[binary]<4.0.0,>=3.1.10->mig25)
```

**Comment by dvarrazzo** [comment] 2024-07-01 03:11
Dupe of #853

**Closed by dvarrazzo** 2024-07-01 03:11 UTC
