### ISSUE TITLE
bug: PoolTimeout on pool with available connections

### ISSUE THREAD

**Issue by Spaxterr** [psycopg/psycopg#219] opened 2022-02-02 16:59 UTC
I'm running a global AsyncConnectionPool that I use in various classes in my project, which seems to be working fine. However, after running the pool for a few hours, it stops giving connections despite having many available ones.

`PoolTimeout: couldn't get a connection after 30.0 sec`

This seems to happen at random after keeping the pool active for about an hour.

Here's the code I use to initialize the pool
```py
global pool


async def start_pool():
    global pool
    pool = AsyncConnectionPool(conninfo=f"""
            host=localhost
            port=5432
            dbname=database
            user=username
            password=password
        """)
    await pool.resize(32, 512)  # Pool size set to large number for testing purposes
```
And here's an example of how I'm using it 
```py
    async def get_stats(self):
        sql = """SELECT * FROM stats WHERE user_id=%s"""
        sqldata = (self.user_id,)
        async with self.pool.connection() as conn:
            async with conn.cursor(row_factory=dict_row) as cur:
                await cur.execute(sql, sqldata)
                result = await cur.fetchone()
        return result
```
Here's the values recieved from `pool.get_stats()` when the issues start to happen:
```js
{'requests_num': 74, 
'requests_queued': 9,
'connections_num': 9, 
'connections_ms': 130, 
'requests_wait_ms': 240030, 
'usage_ms': 1249, 
'requests_errors': 8, 
'pool_min': 32, 
'pool_max': 512, 
'pool_size': 33, 
'pool_available': 0, 
'requests_waiting': 8}
```

Note that I increased the `max_size` to a pretty large number just to see if it was the size causing the issues, but clearly it is not. Either I missed something in the documentation, or something is wrong under the hood.

**Comment by dvarrazzo** [comment] 2022-02-03 11:36
@Spaxterr pool_available = 0 seems to suggest that there are no connections in the pool.

Could you please provide a self-contained script to reproduce the issue?

Thank you very much

**Comment by Spaxterr** [comment] 2022-02-03 15:23
I'll set up a test script and run it for an hour or so to see if the same issues occur there, thank you for your response. I understand that there are 0 connections in the pool, but I am struggling to understand why since I am using the context manager and set the min_connections = 32

**Comment by dvarrazzo** [comment] 2022-02-03 16:11
Thank you very much!

Please note that you may enable the `psycopg.pool` logger to get a log of the pool operations: it should be useful to debug the issue.

Something that seems strange in your stata is that the pool seems to have obtained only 9 connections from the server although it has several connection jobs pending, because the min is 32. It would be interesting to see the log and understanding what the workers are doing.

I also see that the connections obtained requested a total of 4 minutes. I guess that's consistent with the 8 requests failed with a default timeout of 30 seconds.

**Comment by Spaxterr** [comment] 2022-02-04 08:24
Thank you for the tip, I have temporarily re-written the logic to no longer use a connection pool and it seems to be working just fine. Oddly enough, the test script I wrote has been running for several hours now without issues so there might have been an unnoticed mistake from my part. Thank you for your assistance.

**Comment by dvarrazzo** [comment] 2022-05-09 00:31
I assume this can be closed then, but if you have any suspect that the problem is still there please let us know. Thank you!

**Comment by w4tsn** [comment] 2022-11-03 14:26
I'd like to file another report for this issue: I'm also using the `AsyncConnectionPool` and it's context managers (for `connection()` and `cursor()`) and I'm also seeing this behavior, that after the `max_lifetime` is reached, the connection pool is emptied and stays at 0 available connections.

I've enabled the debug logging and found out that at startup (I'm using FastAPI and it's async startup method, so everything is in the same async eventloop) the pool is filled with `pool_min` connections (`adding new connection to the pool`) and after the at first connections are served and returned as expected. After `max_lifetime` is reached however the connections are discarded after being returned to the pool (`discarding expired connection`) and I see a pool growth exactly once (`growing pool 'test' to 5`). It's always just a growth of 1, although there might be 8 requests queued. The queued requests then all fail with a timeout error.

My stats look exactly like the ones from the first report. This state is reproducible. After a restart of the FastAPI application everything works fine until `max_lifetime` time has passed. Then all connections are discarded one after another (depending on how many requests are made of course) and the pool is not filled with new connections by itself.

In my code I don't do anything more (psycopg wise) than opening the pool in FastAPI startup and then using a global custom contextmanager which invokes the connection and cursor context managers and yields their result so I can except errors for logging and http error responses. I first thought that the connections might not be returned but the debug log suggests otherwise. The debug log suggests, that after the initial connection creation no new connections are created on further requests.

An example code (no full reproducer) of the context manager opening a connection context:

```
@asynccontextmanager
async def get_connection() -> AsyncIterator[psycopg.AsyncConnection]:
    """Get a connection context from the pool"""
    try:
        async with CONNECTION_POOL.connection() as connection:
            yield connection
    except psycopg.InterfaceError as error:
        logger.error(
            "DB transaction failed. psycopg.InterfaceError: %s",
            error,
        )
        logger.debug(
            "Pool '%s' stats: %s", pool.name, str(CONNECTION_POOL.get_stats())
        )
        raise error
    except (psycopg.DatabaseError, psycopg.InternalError) as error:
        logger.error(
            "DB transaction failed. Reverting all uncommitted operations of transaction. psycopg.Error: %s",
            error,
        )
        logger.debug(
            "Pool '%s' stats: %s", pool.name, str(CONNECTION_POOL.get_stats())
        )
        raise error
```

**Comment by dvarrazzo** [comment] 2022-11-03 15:39
Thank you for the report, @w4tsn. I would have opened this as a new issue. Reopening this.

The pool is designed to grow one connection at time, to avoid that a sudden burst in connections needed starves other tasks (for instance the cleanup ones returning the tasks). Of course if `AddConnection` is never executed that's a problem. A problem in this area was fixed in #370: are you sure you are using psycopg_pool least 3.1.2?

**Comment by w4tsn** [comment] 2022-11-03 15:51
@dvarrazzo hey there! I'm using 3.1.4 right now.

I've made a discovery: I've followed up on my suspicion about the time when asyncio.Queue() get's created. I've added `pool._tasks = asyncio.Queue()` function to the async startup function of FastAPI (the asgi app/framework in use). I reduced the `max_lifetime` to 30 seconds to see results faster and indeed I double checked: after doing this little workaround tasks are executed as expected.

My guess it it would be safer to create the Queue() object inside an async `open()` function the same way as the creation of connections can be delayed.

**Comment by dvarrazzo** [comment] 2022-11-03 15:54
@w4tsn I think you are right regarding the pool having problems when it's created before the loop started :)

```python
import asyncio
import logging
from psycopg_pool import AsyncConnectionPool

logger = logging.getLogger()
logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logging.getLogger("psycopg.pool").setLevel(logging.DEBUG)

pool = AsyncConnectionPool("host=localhost", max_lifetime=10, open=False)


async def main() -> None:
    # pool = AsyncConnectionPool("host=localhost", max_lifetime=10, open=False)
    await pool.open()
    logger.info("sleeping")
    for i in range(30):
        async with pool.connection() as conn:
            cur = await conn.execute("select now()")
            ts, = await cur.fetchone()
            logger.info("time: %s", ts)
        logger.info("pool_available: %s", pool.get_stats().get("pool_available"))
        await asyncio.sleep(1)
    logger.info("slept")


asyncio.run(main())
```

this script reproduces the issue: after about 10s the `pool_available` starts decreasing and stays at 0.

If the pool is created in `main()`, where the commented-out line is, it works as expected.

**Comment by w4tsn** [comment] 2022-11-03 15:59
Should it be safe to create the pool before the loop started? I'm creating the pool in a module top-level as a variable I then import at other parts of the software because I didn't want to create a singleton class (see it as unnecessary complexity here).

Or is this expected and I should not create the pool before the loop started?

**Comment by dvarrazzo** [comment] 2022-11-03 16:07
No, it's not expected. I will take a look if the pool is salvageable in the form it is now, by creating the internal queues and other asyncio-related objects only on `open()`, or if instead we should just discourage to initialize the pool before the loop has started.

**Comment by dvarrazzo** [comment] 2022-11-03 16:24
Looks like we can fix the problem with:

```diff
--- a/psycopg_pool/psycopg_pool/pool_async.py
+++ b/psycopg_pool/psycopg_pool/pool_async.py
@@ -47,11 +47,13 @@ class AsyncConnectionPool(BasePool[AsyncConnection[Any]]):
         # to notify that the pool is full
         self._pool_full_event: Optional[asyncio.Event] = None
 
-        self._sched = AsyncScheduler()
         self._sched_runner: Optional[Task[None]] = None
-        self._tasks: "asyncio.Queue[MaintenanceTask]" = asyncio.Queue()
         self._workers: List[Task[None]] = []
 
+        # asyncio objects, created on open to attach them to the right loop.
+        self._sched: AsyncScheduler
+        self._tasks: "asyncio.Queue[MaintenanceTask]"
+
         super().__init__(conninfo, **kwargs)
 
         if open:
@@ -197,6 +199,11 @@ class AsyncConnectionPool(BasePool[AsyncConnection[Any]]):
 
         self._check_open()
 
+        # Create these objects now to attach them to the right loop.
+        # See #219
+        self._tasks = asyncio.Queue()
+        self._sched = AsyncScheduler()
+
         self._closed = False
         self._opened = True
```

this allows to create the pool as a global variable and just call `await open()` with a loop present.

Most likely the problem cannot be avoided if the pool is created with `open=True`. I think we should deprecate this practice asap.

**Closed** 2022-11-04 16:32 UTC

**Comment by dvarrazzo** [comment] 2022-11-04 17:39
psycopg_pool 3.1.4 released, with this bug fix.

@w4tsn a note about version number:

> hey there! I'm using 3.1.4 right now.

psycopg and psycopg_pool release numbers are independent, they just happen to be very close by chance. So most likely you were testing with psycopg_pool 3.1.3 and psycopg 3.1.4.

Thank you very much for the report and the help with fixing it!
