### ISSUE TITLE
Improper handling of keyword arguments in connection pools

### ISSUE THREAD

**Issue by oceyral** [psycopg/psycopg#458] opened 2022-12-13 14:29 UTC
Hi,

The documentation for connection pools states [here](https://www.psycopg.org/psycopg3/docs/api/pool.html#psycopg_pool.ConnectionPool) that the `__init__` can take `**kwargs` that are further passed to `connect()`, and connect states [here](https://www.psycopg.org/psycopg3/docs/api/connections.html#psycopg.Connection.connect) that those kwargs are used to override parameters in the `conninfo` string.

This should work : 
```python
async with AsyncConnectionPool(dbname='test', user='test', password='very_secure') as async_pool:
    [...]
```
But instead, I get the following error : 
```
  File "/home/oceyral/dev/dbtest/./main.py", line 135, in main
    async with AsyncConnectionPool(**conn_parameters) as async_pool:
  File "/home/oceyral/.cache/pypoetry/virtualenvs/dbtest-sP59csmC-py3.10/lib/python3.10/site-packages/psycopg_pool/pool_async.py", line 57, in __init__
    super().__init__(conninfo, **kwargs)
TypeError: BasePool.__init__() got an unexpected keyword argument 'dbname'
```

It looks like it's caused by [`ConnectionPool`](https://github.com/psycopg/psycopg/blob/master/psycopg_pool/psycopg_pool/pool.py#L56) and [`AsyncConnectionPool`](https://github.com/psycopg/psycopg/blob/master/psycopg_pool/psycopg_pool/pool_async.py#L57) calling `BasePool` with `super().__init__(conninfo, **kwargs)`, but `BasePool` only expects `kwargs` as an actual argument [here](https://github.com/psycopg/psycopg/blob/master/psycopg_pool/psycopg_pool/base.py#L44), instead of as actual keyword arguments.

Psycopg version: 3.1.4

**Comment by dvarrazzo** [comment] 2022-12-13 15:06
Documentation also says:

> kwargs (dict) – Extra arguments to pass to `connect()`. Note that this is _one dict argument_ of the pool constructor, which is expanded as `connect()` keyword parameters.

Duplicate of #341.

**Closed by dvarrazzo** 2022-12-13 15:06 UTC
