### ISSUE TITLE
psycopg type objects aren't hashable

### ISSUE THREAD

**Issue by zzzeek** [psycopg/psycopg#157] opened 2021-11-19 15:23 UTC
I feel like I've reported this for a different PG driver before, we need to make a lookup of psycopg types to string names for casts like this:

```py
        return {
            dbapi.STRING: "varchar",
            dbapi.TIMESTAMP: "timestamp",
            dbapi.TIMESTAMP_W_TZ: "timestamp with time zone",
            dbapi.DATE: "date",
            dbapi.TIME: "time",
            dbapi.INTERVAL: "interval",
            dbapi.NUMBER: "numeric",
            dbapi.FLOAT: "float",
            dbapi.BOOLEAN: "bool",
            dbapi.INTEGER: "integer",
            dbapi.BIGINTEGER: "bigint",
            dbapi.BYTES: "bytes",
            dbapi.DECIMAL: "decimal",
            dbapi.JSON: "json",
            dbapi.JSONB: "jsonb",
            dbapi.ENUM: "enum",
            dbapi.UUID: "uuid",
            dbapi.BYTEA: "bytea",
        }
```

the objects in psycopg aren't hashable though.  i dont see any reason they shouldnt be:

```py
>>> import psycopg
>>> {psycopg.STRING: "string"}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unhashable type: 'DBAPITypeObject'
```

ill work around it for now using `__name__`
cc @CaselIT

**Comment by zzzeek** [comment] 2021-11-19 15:24
also the bigger issue here is that because psycopg uses prepared statements it would be nice if it supported cursor.setinputsizes(), where you take those types and then apply casts to the statement.   pg8000 does this also.  we will emulate it on our end for now

**Comment by zzzeek** [comment] 2021-11-19 15:27
hmm OK you might not even have enough type objects for this to be feasible anyway...

**Comment by zzzeek** [comment] 2021-11-19 16:23
im doing it like this for now

```py
        return {
            dbapi.STRING.name: "varchar",
            dbapi.adapters.types["integer"].name: "integer",
            dbapi.adapters.types["date"].name: "date",
            dbapi.adapters.types[
                "timestamptz"
            ].name: "timestamp with time zone",
            dbapi.adapters.types["timestamp"].name: "timestamp",
        }
```

that is, mixing the "adapters" and the fixed objects together and just using "name" to get something hashable.

**Comment by dvarrazzo** [comment] 2021-11-20 00:36
Hello @zzzeek,

It didn't occur me that you could use setinputsizes with types. It's something that could be considered for the next 3.1 verson, if it makes SQLAlchemy life easier. We have a similar method for the copy object, [set_types()](https://www.psycopg.org/psycopg3/docs/api/cursors.html#psycopg.Copy.set_types), where is required in certain cases. We can consider implementing something similar for the cursor too.

As for having hashable things, wourl making the `dbapi.adapters.type` entries hashable useful? The top-level entries don't seem complete: we expose the ones minimally required by the DBAPI, but others (UUID, JSON...) are not a standard, AFAIK. Or am I wrong?

**Comment by zzzeek** [comment] 2021-11-20 00:51
I agree your top level entries aren't that complete.  but they could be.  you can add as many as you'd like, like [pg8000 has](https://github.com/tlocke/pg8000/blob/master/pg8000/converters.py).    For our end, we don't actually need the "oid" part of this, we need to be able to send this to the driver and say, "make sure this parameter is treated like TIMESTAMP WITH TIMEZONE".

IIUC the psycopg2 driver is doing more here to make sure there's a "::cast" for incoming bound parameters, is that correct?  at the same time it seems like using prepared statements with postgresql seems to require a lot more specific typing information ?

**Comment by zzzeek** [comment] 2021-11-23 17:57
just an update my current plan is that we will standardize a new system on our end that renders the casts for us, without using any DBAPI symbols.   I have this in review applied to psycopg2 / asyncpg / pg8000 consistently and it will apply here pretty well also.   I also noticed that psycopg2's type objects arent hashable either, I just never needed them to be.

so from my POV I dont need anything here right now.

**Comment by dvarrazzo** [comment] 2021-11-23 18:38
Hi @zzzeek 

> IIUC the psycopg2 driver is doing more here to make sure there's a "::cast" for incoming bound parameters, is that correct? at the same time it seems like using prepared statements with postgresql seems to require a lot more specific typing information ?

psycopg2 "decorates" some of the values it casts with a `::cast`, making them effectively a snippet of SQL. This might have not been a happy choice, it was made aeons ago once when PostgreSQL changed their cast rules, breaking many queries; the answer might has well been to tell our users "blame them and suffer" :slightly_smiling_face: but we felt responsible to smoothen the blow. However it's not the only place where psycopg2 generates SQL snippets rather than just values: it does so using the `ARRAY[]` construct for instance. Apart from building the query string, however, it doesn't pass information to the server in any other way.

Psycopg 3 cannot follow the same practice because the "extended query protocol" (aka server-side binding) only takes values, not SQL snippets. On the other hand, the same protocol allows to specify an optional type information too for each placeholder. The two ways don't produce exactly the same result; some of the intricacies found [are described here](https://www.varrazzo.com/blog/2020/11/07/psycopg3-adaptation/).

> so from my POV I dont need anything here right now.

In this case I'll close this ticket but please feel free to let us know if you need any support.

Cheers!

**Closed by dvarrazzo** 2021-11-23 18:38 UTC

**Comment by zzzeek** [comment] 2021-11-23 20:30
>  On the other hand, the same protocol allows to specify an optional type information too for each placeholder. 

right, so if psycopg3 were to have a .setinputsizes() type of method, this would allow you to pass a sequence of OIDs separately (as stated [here](https://www.postgresql.org/docs/10/protocol-flow.html#PROTOCOL-FLOW-EXT-QUERY)), vs. having "%s::type" embedded in the SQL.    So you are saying there are some differences in behavior there?  I looked over your blog post but didnt see mention of the two argument-passing styles.

**Comment by dvarrazzo** [comment] 2021-11-23 22:00
The difference is more like: "SELECT 10" will return you an int4, "SELECT 10000000000000" an int8, more digits and will return you a numeric. The literal behaves like an "unknown but number", and can be only obtained at SQL level (and with client-side binding: psycopg2 has done it all the time).

There is no way that I have found to get the same effect with server-side binding: passing a "SELECT $1" query and some type. You can only specify a type oid such as int4, itn8, numeric: too small and it will likely overflow; too large and Postgres will not select a _cast down_ to a smaller type, neither in a data field nor as parameter to any function or operator, many of which ('LEFT(text, int)', '-> (json, int)'...) are defined int4 only. Alternatively, you can specify unknown oid, but in that case the number is returned back as text (and in Postgres <= 9.6 in an error: if I had started to work on psycopg3 earlier I would have given up).

The only escape hatch is that postgres can implicitly _cast up_ instead (no overflow possible), so you can pass an int2 value to an int4 parameter. Using that feature we could at least implement the [`get_key()/upgrade()`](https://www.psycopg.org/psycopg3/docs/api/abc.html#psycopg.abc.Dumper.get_key) mechanism, which allows to look at the value of a Python object, after having looked at its type, and to select the smallest Postgres numeric type possible to represent such value, or the most appropriate type, e.g. in the timestamp(tz?) case. This sort of reproduce the same "anynumber" available in flat SQL and makes psycopg 3 not a pain to use.

About implementing `setinputsizes()` I have opened #163. I wouldn't know how to make anything useful of it if I received a `psycopg.NUMBER` though, for the reason that now should be clear, so I'd make it take a sequence of strings such as `datetimetz, int8[]`, or their oids, and look up for the right Dumper in the cursor adapters map. Passing it `TypeInfo` instances doesn't seem useful either (it might be a type or its array), if any it might take a list of Dumper object, but why...
