### ISSUE TITLE
Can't pass empty password in psycopg.connect. Seeing psycopg.OperationalError: connection failed: fe_sendauth: error sending password authentication

### ISSUE THREAD

**Issue by kahmad-dev** [psycopg/psycopg#765] opened 2024-04-04 07:30 UTC
I am trying to migrate from psycopg2 to psycopg3. When i am making connection with psycopg3 I am facing below error while this works fine with psycopg2. 

ERROR:
`psycopg.OperationalError: connection failed: fe_sendauth: error sending password authentication`

> Note: I see same error with key:value and connection string formats.  

https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING

With psycopg2 connection creation passed
=========================================
```
>>> import psycopg2
>>> psycopg2.__version__
'2.9.9 (dt dec pq3 ext lo64)'
>>> connection_str = "dbname='machinedb' host='localhost' user='postgres' password=''"

# Connection successfull
>>> conn = psycopg2.connect(connection_str)
>>> dir(conn)
['DataError', 'DatabaseError', 'Error', 'IntegrityError', 'InterfaceError', 'InternalError', 'NotSupportedError', 'OperationalError', 'ProgrammingError', 'Warning', '__class__', '__delattr__', '__dir__', '__doc__', '__enter__', '__eq__', '__exit__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'async', 'async_', 'autocommit', 'binary_types', 'cancel', 'close', 'closed', 'commit', 'cursor', 'cursor_factory', 'deferrable', 'dsn', 'encoding', 'fileno', 'get_backend_pid', 'get_dsn_parameters', 'get_native_connection', 'get_parameter_status', 'get_transaction_status', 'info', 'isexecuting', 'isolation_level', 'lobject', 'notices', 'notifies', 'pgconn_ptr', 'poll', 'protocol_version', 'readonly', 'reset', 'rollback', 'server_version', 'set_client_encoding', 'set_isolation_level', 'set_session', 'status', 'string_types', 'tpc_begin', 'tpc_commit', 'tpc_prepare', 'tpc_recover', 'tpc_rollback', 'xid']
>>>
```

With psycopg3 Failed
====================
```
>>> import psycopg
>>> psycopg.__version__
'3.1.18'
>>> connection_str = "dbname='machinedb' host='localhost' user='postgres' password=''"

# Connection failed
>>> conn2 = psycopg.connect(connection_str)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<mypath>/psycopg/connection.py", line 748, in connect
    raise last_ex.with_traceback(None)
psycopg.OperationalError: connection failed: fe_sendauth: error sending password authentication
```

**Comment by dvarrazzo** [comment] 2024-04-04 10:07
I don't see anything obviously wrong in the handling of an empty password, quoted or unquoted.

Can you connect to the same database using the connection string with quoted and with unquoted password?

```
psql "dbname='machinedb' host='localhost' user='postgres' password=''"
psql "dbname='machinedb' host='localhost' user='postgres' password="
```

What database is this? Pure postgres or something else?

**Comment by kahmad-dev** [comment] 2024-04-04 10:23
Machine has two postgres versions i.e. 13 and 14 version. Default psql version is 14 (see below)

# Default version
```
root@cloud-builder [ /opt/vmware ]# psql --version
psql (PostgreSQL) 14.10
```


# psql version in machine
```
root@machine## ls -ls /usr/pgsql/
total 8
4 drwxr-xr-x 5 root root 4096 Mar 21 22:15 13
4 drwxr-xr-x 5 root root 4096 Dec  6 07:20 14
```



I can connect to postgres using psql but with v13 binary howver with v14 i see the error

# Connection succesfful with psql (13.14)
```
root@machine# /usr/pgsql/13/bin/psql -U postgres -h localhost
psql (13.14)
Type "help" for help.

postgres=# \conninfo
You are connected to database "postgres" as user "postgres" on host "localhost" (address "127.0.0.1") at port "5432".
postgres=# \q
```


# Connection issue with psql (PostgreSQL) 14.10

```
root@machine#/usr/pgsql/14/bin/psql -U postgres -h localhost
psql: error: connection to server at "localhost" (127.0.0.1), port 5432 failed: fe_sendauth: error sending password authentication
```


Does psycopg3 depends on psql? If yes, can we specify during connection creation?

**Comment by dvarrazzo** [comment] 2024-04-04 12:32
No, it doesn't depend on psql, but both psql and psycopg use the same connection library so the connection string will be interpreted the same way. But you need to specify the connection string as you provide to psycopg, not separate parameters such as `-U` or `-h`.

Can you test the two commands suggested? With the connection string exactly as passed to psycopg (in quotes so that bash sees it as a single parameter).

Thank you very much.

**Comment by dvarrazzo** [comment] 2024-04-04 17:16
Thank you, this is an interesting finding, and it points to a difference in behaviour between libpq 13 and 14.

However this doesn't provide us a solution, because using libpq 13 in binary packages is not an option: several psycopg features depend on a newer libpq.

You didn't answer one of my questions: what happens if you connect using an empty unquoted string in psql 14? I.e. running

```
/usr/pgsql/14/bin/psql "dbname='machinedb' host='localhost' user='postgres' password="
```

if this work we can try and make sure to generate unquoted strings for empty parameters.

**Comment by dvarrazzo** [comment] 2024-04-04 17:18
It would be also interesting to check which versions of libpq psycopg is actually using. You can use the following for psycopg 3 and 2:

```python
>>> import psycopg
>>> psycopg.pq.version()
160002

>>> import psycopg2
>>> psycopg2.extensions.libpq_version()
150003
```

**Comment by kahmad-dev** [comment] 2024-04-05 06:32
> You didn't answer one of my questions: what happens if you connect using an empty unquoted string in psql 14? I.e. running
> 
> ```
> /usr/pgsql/14/bin/psql "dbname='machinedb' host='localhost' user='postgres' password="
> ```
> 
> if this work we can try and make sure to generate unquoted strings for empty parameters.

I missed this. I checked and I see the same error:

```
machine # /usr/pgsql/14/bin/psql "dbname='machinedb' host='localhost' user='postgres' password="
psql: error: connection to server at "localhost" (127.0.0.1), port 5432 failed: fe_sendauth: error sending password authentication
```

They are using different versions.  So, as i understand -  psycopg2 is using libpq packaged version where as for psycopg3 is using system default, and with system default it fails - is this understanding correct? Also, is there was to set or change this default version. As we see with v13 we are able to connect successfully and by default psycopg3 is using 14, so how can i change to 13 and test - can i patch and test?


Available libpq versions
```
machine]# find / -name libpq.so*
/usr/pgsql/13/lib/postgresql/libpq.so.5.13
/usr/pgsql/13/lib/postgresql/libpq.so.5
/usr/pgsql/13/lib/postgresql/libpq.so
/usr/pgsql/14/lib/postgresql/libpq.so.5.14
/usr/pgsql/14/lib/postgresql/libpq.so.5
/usr/pgsql/14/lib/postgresql/libpq.so

<psycopg2 path>/psycopg2_binary.libs/libpq-e8a033dd.so.5.16.        -> from psycopg2 package
```



> It would be also interesting to check which versions of libpq psycopg is actually using. You can use the following for psycopg 3 and 2:

Yes there are different versions

```
>>> import psycopg
>>> psycopg.pq.version()
140010

>>> import psycopg2
>>> psycopg2.extensions.libpq_version()
160000
```

**Comment by dvarrazzo** [comment] 2024-04-05 09:19
> They are using different versions. So, as i understand - psycopg2 is using libpq packaged version where as for psycopg3 is using system default, and with system default it fails

If you are using `psycopg2-binary` or `psycopg[binary]` they will bring their own libpq packaged. Otherwise they will use the system version.

> Yes there are different versions

From the version you posted it seems that there is a bug in libpq 14 that was fixed in libpq 16, which your psycopg2 version is using. Therefore you seem to need to upgrade the libpq on your system, or to use a binary version of psycopg 3 packaging a more modern libpq.

Which libpq wrapper are you using (you can check it with [`psycopg.pq.__impl__`](https://www.psycopg.org/psycopg3/docs/api/pq.html#pq-module-implementations))? I assume it is `python` or `c`. Can you `pip install psycopg[binary]`, check that `psycopg.pq.__impl__ == "binary" and that `psycopg.pq.version() == 160000` and test again?

Also... what is the password of your database? If you connect with `psql "dbname='machinedb' host='localhost' user='postgres'"` are you asked to enter a password? If so, is it an empty string or two single quotes `''`?

**Comment by dvarrazzo** [comment] 2024-04-05 10:34
> No password asked, user directly enters in psql shell.

I don't understand what's your setup in `pg_hba.conf` but... how about you don't pass the `password` parameter, instead of passing an empty string, if the user doesn't have a password?

**Comment by kahmad-dev** [comment] 2024-04-05 11:01
> I don't understand what's your setup in pg_hba.conf but... how about you don't pass the password parameter, instead of passing an empty string, if the user doesn't have a password?

Its the same thing, when i connect using psql we dont  need to provide 'password' attribute at all, it works.  So, basically locally, for root user, there is no password asked by psql

**Comment by dvarrazzo** [comment] 2024-04-05 11:06
What I'm saying is that your setup has something strange, because it's not like yours is the first system we see with a user without a password. I wonder what triggers that difference with the libpq versions. However, for what this project is concerned, if updating to libpq 16 fixes the problem you find, I am satisfied with that.

**Comment by kahmad-dev** [comment] 2024-04-05 11:17
I see it works with psycopg_binary, I Installed psycopg_binary and tried to connect, saw below failure, so also need to install psycopg 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/psycopg-bin/psycopg_binary/__init__.py", line 12, in <module>
    raise ImportError("the psycopg package should be imported before psycopg_binary")
ImportError: the psycopg package should be imported before psycopg_binary
```


local package
```
[ ~/psycopg-bin ]# ls
psycopg_binary  psycopg_binary-3.1.18.dist-info  psycopg_binary.libs
[ ~/psycopg-bin ]# pip3 install psycopg -t ./
Collecting psycopg
  Using cached psycopg-3.1.18-py3-none-any.whl (178 kB)
Collecting typing-extensions>=4.1
  Using cached typing_extensions-4.10.0-py3-none-any.whl (33 kB)
Installing collected packages: typing-extensions, psycopg
Successfully installed psycopg-3.1.18 typing-extensions-4.10.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

```

Error
```
>>> import psycopg_binary
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/psycopg-bin/psycopg_binary/__init__.py", line 12, in <module>
    raise ImportError("the psycopg package should be imported before psycopg_binary")
ImportError: the psycopg package should be imported before psycopg_binary

```


connection successfull
```
>>> import psycopg
>>> connection_str = "dbname='machinedb' host='localhost' user='postgres' password=''"
>>> conn2 = psycopg.connect(connection_str)
>>> psycopg.pq.version()
160000
```


So do we need to keep both psycopg and psycopg_binary to make it work?

**Comment by dvarrazzo** [comment] 2024-04-05 11:43
Yes, `psycopg_binary` is an implementation module, which should be installed with the extra dependency `psycopg[binary]` to get a compatible version. Once installed you will still use `psycopg` in your code, but you get the speedup of the C extension, which is precompiled and bundled with the requested libraries. All the details are [in the docs](https://www.psycopg.org/psycopg3/docs/basic/install.html).

Anyway, it seems that libpq 16 works with your setup. If you want to understand better the difference between libpq 14 and 16 you will need to ask a postgres ML, such as pgsql-general. I am not able to reproduce your issue: if an user has no password I am able to connect specifying any password.

We are not making mistakes in parsing quoted empty strings in psycopg, as I originally thought it was the case. So I think we can close this issue here.

**Closed by dvarrazzo** 2024-04-05 11:43 UTC

**Comment by kahmad-dev** [comment] 2024-04-05 12:38
It's worth documenting libq version specific dependency when using psycopg module. There is no easy way to debug rather its super misleading. 


`psycopg.OperationalError: connection failed: fe_sendauth: error sending password authentication`

**Comment by dvarrazzo** [comment] 2024-04-05 15:58
Psycopg has no problem with your libpq version. Your database configuration seems to have a problem with libpq <15 or <16. I have no idea about that problem, and I'm 100% sure that you could connect to a database with a user without a password way before postgres 14.

Therefore I invite you to have a conversation about this issue with Postgres developers. We are only the messengers that forwarded you an error message between the client library and server here.
