### ISSUE TITLE
AsyncNullConnectionPool loop problem

### ISSUE THREAD

**Issue by MnrBnm** [psycopg/psycopg#322] opened 2022-06-22 15:49 UTC
Hi,

Im having a problem with AsyncNullConnectionPool. I have different endpoints api (django rest framework) and each time i call a specific endpoint, I delete a row in my table (everything works fine). 

The problem is when I call my endpoint (and therefore remove rows from my db) very quickly I get an error.  Here is a quick example : 

```
for i in range (10):
     reach_endpoint() 
```

```
// function called when the endpoint is reached

async def do_stuff (..):
   // do stuff such as call another endpoint etc 
  // remove now element from db
 // This is how I connect to my pool 
 async with pool.connection() as conn: // The error happens in this line 
                async with conn.cursor(row_factory=dict_row) as cur:
                    await cur.execute(...) 
```

The error that I'm getting is the following : 

```
RuntimeError: Task <Task pending name='Task-36' coro=<AsyncToSync.main_wrap() running at /Users/kk/PycharmProjects/API/venv/lib/python3.9/site-packages/asgiref/sync.py:270> cb=[_run_until_complete_cb() at /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py:184]> got Future <Future pending created at /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py:424> attached to a different loop
```

It's very strange because when I don't call my endpoint in a for loop, it works fine. I guess it's because I'm trying to access the pool too quickly ? I know that it can be difficult to debug stuff like that especially when it's related to the async loop  (I've already looked at all the SO questions related to that without any success ) 

Thx in advance !!

**Comment by dvarrazzo** [comment] 2022-06-22 19:50
Hi,

looking at your error message it seems you are closing and reopening the asyncio loop in your for loop.

I don't even see psycopg objects mentioned in the error you get. Wrapping it for readability:

```
RuntimeError: Task <Task pending name='Task-36' coro=<AsyncToSync.main_wrap()
running at /Users/kk/PycharmProjects/API/venv/lib/python3.9/site-packages/asgiref/sync.py:270>
    cb=[_run_until_complete_cb() 
    at /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py:184]>
got Future
    <Future pending created at /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py:424>
attached to a different loop
```

What I think happens that a request of your framework is not completed correctly and a following request, when it hits the asyncio machinery (in `pool.getconn()`) tries to close tasks that now have been GC'd, and they find a different loop running.

I don't believe there is any problem in psycopg here, I think that the problem is in asgiref or in the way you use it. If you can provide a self-contained example we can look into it, but as it is I don't see any problem in the code snipped you posted.

**Closed by dvarrazzo** 2022-06-22 19:50 UTC

**Comment by dvarrazzo** [comment] 2022-06-27 12:42
Django is, fundamentally, a sync framework. I understand you are going from an async web server, to a sync framework, to an async code path in psycopg. I don't think this can go well: it seems that your framework opens and closes the loop continuouslyand nothing in your error message suggests is a psycopg problem.

If you are using Django/DRF, I think you should stick to sync libraries.
