### ISSUE TITLE
Regression for support of multiple hosts with `target_session_attrs` comparing to psycopg2

### ISSUE THREAD

**Issue by moonrail** [psycopg/psycopg#602] opened 2023-07-12 15:46 UTC
Hello altogether,

first off thank you for work on v3 and psycopg2 before that.

There may be a regression of functionality in v3 in how connections are opened.

Basically it seems that psycopg2 can handle unreachable hosts correctly while v3 cannot. Maybe due to SSL negotiation:
```python
  File "/tmp/test_psycopg/venv/lib64/python3.11/site-packages/psycopg/connection.py", line 728, in connect
    raise ex.with_traceback(None)
psycopg.OperationalError: connection failed: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
could not send SSL negotiation packet: Success
```

From my testing the above behaviour is the same if the IP is not reachable or the port is down.

This is problematic when using the multi-host feature with `target_session_attrs` of PostgreSQL:
- https://www.postgresql.org/docs/14/libpq-connect.html#LIBPQ-CONNSTRING
- https://www.postgresql.org/docs/14/libpq-connect.html#LIBPQ-CONNECT-TARGET-SESSION-ATTRS

With this feature a DSN could be e.g.:
`postgresql://username:password@host1,host2,host3/dbname?target_session_attrs=read-write`

With psycopg2 a network downtime of host1 (port down, IP not reachable via TCP) would lead to host2 to be tried for a read-write session and after that host3, and from the beginning. This is useful when having automatic failovers in a PostgreSQL-Cluster.

With v3 and all hosts reachable the feature works correctly and the first host with desired `target_session_attrs` is selected.

### Steps to reproduce

This "ssl" error is easy to reproduce:
1. setup a postgresql host, reachable via TCP
2. try to connect to it:
```python
import psycopg

conn = psycopg.connect(f"postgresql://username:password@host1")
print(conn.info.host)
print(conn.cursor().execute('SELECT 1;'))
```
3. now stop postgresql on the host
4. retry with the same script

For testing with multi host a cluster is not required, just two postgresql hosts with the same credentials:
1. setup 2 postgresql hosts, reachable via TCP
2. create the same user on both
3. try to connect to it:
```python
import psycopg

conn = psycopg.connect(f"postgresql://username:password@host1,host2")
print(conn.info.host)
print(conn.cursor().execute('SELECT 1;'))
```
4. now stop postgresql on host1
5. retry with the same script

The connection should be made to host2, but it already fails with host1.

**Comment by dvarrazzo** [comment] 2023-07-23 19:05
Hello,

I don't think this is a psycopg bug: psycopg doesn't do anything special with the connection address and has no specific use of target_session_attrs.

It is more likely that this difference is due to different libpq version. Which libpq version are you using with psycopg 2 and 3?

**Comment by moonrail** [comment] 2023-07-24 11:28
Hello @dvarrazzo 
both libaries were testet with libpq "140003" as reported by:

```python
psycopg2.__libpq_version__
psycopg.pq.__build_version__
```

Which should be 14.3, as I have used PostgreSQL 14.3 for testing.

I've re-tested it right now - it is still present, with the same libpq version.

**Comment by dvarrazzo** [comment] 2023-07-24 12:49
One difference between psycopg 2 and 3 is that the internal work is async in psycopg 3. In 2, it is only async for async and green connections.

Could you please try with psycopg2 in green mode? This can be done by calling `psycopg2.extensions.set_wait_callback(psycopg2.extras.wait_select)`. If psycopg2 fails this way then the problem might be related to the libpq async connection procedure.

**Comment by moonrail** [comment] 2023-07-24 13:54
@dvarrazzo 
No change, psycopg2 works properly even with:
```python
import psycopg2
import psycopg2.extras

psycopg2.extensions.set_wait_callback(psycopg2.extras.wait_select)

...
```

**Comment by dvarrazzo** [comment] 2023-07-24 14:22
Gumble... thank you for your tests. I will try to replicate your testing setup on my box.

**Comment by dvarrazzo** [comment] 2023-08-01 02:38
I could reproduce the issue, but I'm pretty baffled and can't understand yet where it is coming from.

I have a docker running on 192.168.64.3, started using `docker run --rm -e POSTGRES_PASSWORD=password postgres:13`, nothing on 192.168.64.4.

This script works on psycopg2:

<details>

```python
# test-pg3-602.py

import os
os.environ["PSYCOPG_DEBUG"] = "1"

import psycopg2
import psycopg2.extras

psycopg2.extensions.set_wait_callback(psycopg2.extras.wait_select)
# conn = psycopg2.connect("postgres://postgres:password@192.168.64.3")
conn = psycopg2.connect("postgres://postgres:password@192.168.64.4,192.168.64.3")
# conn = psycopg2.connect("postgres://postgres:password@192.168.64.4,192.168.64.3?sslmode=disable")
print(f"{conn.info.host=}")
```

</details>

If built in debug mode, the output looks like the following:

<details>

```
$ python test-pg3-602.py 
[3092077] psycopgmodule: initializing psycopg 2.9.6 (dt dec pq3 ext lo64)
[3092077] psycopgmodule: configuring libpq libcrypto callbacks 
[3092077] psycopgmodule: initializing module constants
[3092077] psycopgmodule: initializing module types
[3092077] psycopgmodule: initializing datetime module
[3092077] psycopgmodule: initializing encodings table
[3092077] psycopgmodule: initializing adapters
[3092077] psycopgmodule: initializing basic exceptions
[3092077] psycopgmodule: initializing sqlstate exceptions
[3092077] psycopgmodule: module initialization complete
[3092077] psyco_connect: dsn = 'postgres://postgres:password@192.168.64.4,192.168.64.3', async = 0
[3092077] connection_setup: init connection object at 0x7f2a5f3aa200, async 0, refcnt = 1
[3092077] con_connect: connecting in SYNC mode
[3092077] conn_connect: new green PG connection at 0x55e55df2cdd0
[3092077] psyco_wait
[3092077] conn_poll: status = 0
[3092077] PQstatus = 2
[3092077] conn_poll: status -> CONN_STATUS_SETUP
[3092077] conn_poll: returning 2

[delay here]

[3092077] conn_poll: status = 20
[3092077] PQstatus = 2
[3092077] conn_poll: status -> CONN_STATUS_CONNECTING
[3092077] conn_poll: poll connecting
[3092077] conn_poll: returning 2
[3092077] conn_poll: status = 20
[3092077] PQstatus = 2
[3092077] conn_poll: status -> CONN_STATUS_CONNECTING
[3092077] conn_poll: poll connecting
[3092077] conn_poll: returning 2
[3092077] conn_poll: status = 20
[3092077] PQstatus = 3
[3092077] conn_poll: status -> CONN_STATUS_CONNECTING
[3092077] conn_poll: poll connecting
[3092077] conn_poll: returning 1
[3092077] conn_poll: status = 20
[3092077] PQstatus = 7
[3092077] conn_poll: status -> CONN_STATUS_CONNECTING
[3092077] conn_poll: poll connecting
[3092077] conn_poll: returning 2
[3092077] conn_poll: status = 20
[3092077] PQstatus = 3
[3092077] conn_poll: status -> CONN_STATUS_CONNECTING
[3092077] conn_poll: poll connecting
[3092077] conn_poll: returning 1
[3092077] conn_poll: status = 20
[3092077] PQstatus = 4
[3092077] conn_poll: status -> CONN_STATUS_CONNECTING
[3092077] conn_poll: poll connecting
[3092077] conn_poll: returning 1
[3092077] conn_poll: status = 20
[3092077] PQstatus = 4
[3092077] conn_poll: status -> CONN_STATUS_CONNECTING
[3092077] conn_poll: poll connecting
[3092077] conn_poll: returning 0
[3092077] conn_connect: server standard_conforming_strings parameter: on
[3092077] conn_connect: server requires E'' quotes: NO
[3092077] conn_connect: using protocol 3
[3092077] conn_connect: client encoding: UTF8
[3092077] clear_encoding_name: UTF8 -> UTF8
[3092077] conn_set_fast_codec: encoding=UTF8
[3092077] conn_set_fast_codec: PyUnicode_DecodeUTF8
[3092077] conn_connect: DateStyle ISO, MDY
[3092077] connection_setup: good connection object at 0x7f2a5f3aa200, refcnt = 1
conn.info.host='192.168.64.3'
[3092077] conn_close: PQfinish called
[3092077] connection_dealloc: deleted connection object at 0x7f2a5f3aa200, refcnt = 0
```

(the output above includes the output of the following patch):
```diff
--- a/psycopg/connection_int.c
+++ b/psycopg/connection_int.c
@@ -1077,6 +1077,7 @@ conn_poll(connectionObject *self)
 {
     int res = PSYCO_POLL_ERROR;
     Dprintf("conn_poll: status = %d", self->status);
+    Dprintf("PQstatus = %d", PQstatus(self->pgconn));
 
     switch (self->status) {
     case CONN_STATUS_SETUP:
```
</details>

A similar script for psycopg 3 fails as reported in this issue:

<details>

```python
# test-602.py

import os
os.environ["PSYCOPG_IMPL"] = "python"

import psycopg

import logging
import psycopg
from psycopg import pq
from psycopg.pq._debug import PGconnDebug

logging.basicConfig(level=logging.INFO, format="%(message)s")
logger = logging.getLogger("psycopg.debug")
logger.setLevel(logging.INFO)

assert pq.__impl__ == "python"
pq.PGconn = PGconnDebug

# conn = psycopg.connect("postgres://postgres:password@192.168.64.3")
# print(f"{conn.info.host=}")
conn = psycopg.connect("postgres://postgres:password@192.168.64.4,192.168.64.3")
print(f"{conn.info.host=}")
```

</details>

Execution:

<details>

```
$ python test-602.py 
PGconn.connect_start(b'postgres://postgres:password@192.168.64.4,192.168.64.3')
    <- <psycopg.pq.pq_ctypes.PGconn [STARTED] at 0x7fd558940680>
PGconn.status -> 2
PGconn.connect_poll()
    <- 2
PGconn.socket -> 3

[delay here]

PGconn.status -> 3
PGconn.connect_poll()
    <- 1
PGconn.socket -> 3
PGconn.status -> 7
PGconn.connect_poll()
    <- 0
PGconn.error_message -> b'connection to server at "192.168.64.4", port 5432 failed: server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n'
PGconn.status -> 1
PGconn.error_message -> b'connection to server at "192.168.64.4", port 5432 failed: server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n'
[...]
PGconn.finish()
Traceback (most recent call last):
  File "/home/piro/dev/psycopg3/test-602.py", line 20, in <module>
    conn = psycopg.connect("postgres://postgres:password@192.168.64.4,192.168.64.3")
  File "/home/piro/dev/psycopg3/psycopg/build/__editable__.psycopg-3.2.0.dev1-py3-none-any/psycopg/connection.py", line 729, in connect
    raise ex.with_traceback(None)
psycopg.OperationalError: connection failed: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

</details>

I have created a script performing a simplified version of the connection procedure, using the libpq call in what I believe is the same sequence psycopg2 uses too:

<details>

```python
# test-602-pq.py

import os
os.environ["PSYCOPG_IMPL"] = "python"

import logging
from select import select

from psycopg import pq
from psycopg.pq._debug import PGconnDebug
from psycopg.waiting import Wait

logging.basicConfig(level=logging.INFO, format="%(message)s")
logger = logging.getLogger("psycopg.debug")
logger.setLevel(logging.INFO)

def wait(fd, status):
    fdlist = (fd,)
    if status is Wait.R:
        select(fdlist, (), ())
    elif status is Wait.W:
        select((), fdlist, ())
    else:
        raise Exception(f"unexpected {status=}")


# conn = PGconnDebug.connect_start(
#     b"postgres://postgres:password@192.168.64.3"
# )
conn = PGconnDebug.connect_start(
    b"postgres://postgres:password@192.168.64.4,192.168.64.3"
)

while True:
    if conn.status == pq.ConnStatus.BAD:
        raise Exception(f"connect_start failed: {conn.error_message.decode()}")

    status = conn.connect_poll()

    if status == pq.PollingStatus.OK:
        break
    elif status == pq.PollingStatus.READING:
        wait(conn.socket, Wait.R)
    elif status == pq.PollingStatus.WRITING:
        wait(conn.socket, Wait.W)
    elif status == pq.PollingStatus.FAILED:
        raise Exception(f"connect_poll failed: {conn.error_message.decode()}")
    else:
        raise Exception(f"unexpected poll status: {status}")

print(f"{conn=}")
```

</details>

The result is the same, the output looks like:

<details>

```
PGconn.connect_start(b'postgres://postgres:password@192.168.64.4,192.168.64.3')
    <- <psycopg.pq.pq_ctypes.PGconn [STARTED] at 0x7fd40fec4630>
PGconn.status -> 2
PGconn.connect_poll()
    <- 2
PGconn.socket -> 3

[delay here]

PGconn.status -> 3
PGconn.connect_poll()
    <- 1
PGconn.socket -> 3
PGconn.status -> 7
PGconn.connect_poll()
    <- 0
PGconn.error_message -> b'connection to server at "192.168.64.4", port 5432 failed: server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n'
Traceback (most recent call last):
  File "/home/piro/dev/psycopg3/test-602-pq.py", line 48, in <module>
    raise Exception(f"connect_poll failed: {conn.error_message.decode()}")
Exception: connect_poll failed: connection to server at "192.168.64.4", port 5432 failed: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

</details>

So, as far as I can see, psycopg2 in green mode and psycopg 3 execute the same operations. The libpq used is the same (15.3 from ubuntu package). psycopg2 might set nonblocking mode before polling, but testing this change in `test-602-pq.py` makes no difference. Disabling ssl using `sslmode=disable` in the url makes no relevant difference (connection status SSL_STARTUP=7 is skipped, but same success/failures).

I am out of attempts, for the moment...

**Comment by dvarrazzo** [comment] 2023-10-26 21:41
I did more tests and it appears that psycopg2 gets stuck, indeed, when using an async callback.

This makes sense: the libpq async connection procedure doesn't support a timeout, so it doesn't really know when to move to the next attempt.

I am trying to solve the problem in #675.

**Comment by dvarrazzo** [comment] 2023-11-13 22:48
Closing this because the problem is not with `target_session_attrs` but with the whole support for multiple hosts, which turns out we had to re-implmeent in Python because it is only implemented in the libpq for the sync connection function. So it's a duplicate of #674. It will be fixed in the next release 3.1.13.

**Closed by dvarrazzo** 2023-11-13 22:48 UTC

**Comment by dvarrazzo** [comment] 2023-11-17 17:59
Psycopg 3.1.13 released with this bug fixed. Testing is welcome. Cheers!

**Comment by dvarrazzo** [comment] 2023-11-21 12:17
@moonrail Thank you very much for testing, I'm glad it works :)
