### ISSUE TITLE
On connection failure, PGconn is leaked until finalization

### ISSUE THREAD

**Issue by jchampio** [psycopg/psycopg#565] opened 2023-05-15 18:22 UTC
Hello,

The `connect` generator appears to have no cleanup step (i.e. a call to `PQfinish`) if the generator's `PQconnectPoll` calls fail. This results in resources leaking (or hanging open, in the case of the underlying socket) until the finalizer is called at process exit.

I'm using `psycopg[c]`, if that matters, but from inspection it looks like the implementation in `generators.py` might have the same problem.

Here's a quick and dirty program to illustrate. The "server" causes a connection failure by writing unexpected data to the socket, then waits for the client to close the connection. With the old `psycopg2.connect`, the script correctly exits after raising `OperationalError`. With `psycopg.connect`, the script hangs.

```py
#! /usr/bin/env python3

import socket
import threading

from psycopg import connect
#from psycopg2 import connect  # uncomment to fix the program


class Server(threading.Thread):
    """
    Accepts exactly one Postgres connection, reads a startup packet, writes
    garbage to the socket, and then tries to read more data.
    """
    def __init__(self):
        super().__init__()

        # Listen on localhost.
        self._listener = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        self._listener.bind(("127.0.0.1", 0))
        self._listener.listen(1)

        _, self.port = self._listener.getsockname()

    def run(self):
        sock, _ = self._listener.accept()
        with sock:
            # Read the startup packet.
            data = sock.recv(4096)
            print("startup: ", data)

            # Send some garbage to the client to cause a connection failure.
            sock.send(b"garbage data")

            # Client should disconnect at this point; the recv() call should
            # immediately return with no data. With psycopg 3.1, this call
            # hangs.
            data = sock.recv(4096)
            print("read: ", data)


server = Server()
server.start()

connect(host="127.0.0.1", port=server.port)  # raises OperationalError

# Python will join the server thread at this point. With psycopg2, the program
# exits; with psycopg 3.1, the program hangs.
```

**Comment by dvarrazzo** [comment] 2023-05-16 00:26
Hello,

the PQfinish is called [on PGconn deallocation](https://github.com/psycopg/psycopg/blob/8ec349089b60ff1ea52700b81431183e0f3c9867/psycopg_c/psycopg_c/pq/pgconn.pyx#L46-L50). As such, it is invoked usually as soon as the `conn` object gets out of scope.

Your example maybe shows something different. I will take a look at why psycopg 3 hangs (probably psycopg2 hangs too in green mode), but that doesn't seem showing a resource leak to me, more the mishandling of a certain communication state.

**Comment by dlax** [comment] 2023-05-16 07:36
The `PGconn` instance does not get out of scope when exiting `generators.connect()` because it got bound to the `OperationalError`. E.g.:
```diff
 diff --git a/psycopg/psycopg/generators.py b/psycopg/psycopg/generators.py
index 584fe47b..d3b03348 100644
--- a/psycopg/psycopg/generators.py
+++ b/psycopg/psycopg/generators.py
@@ -76,7 +76,6 @@ def _connect(conninfo: str) -> PQGenConn[PGconn]:
             encoding = conninfo_encoding(conninfo)
             raise e.OperationalError(
                 f"connection failed: {pq.error_message(conn, encoding=encoding)}",
-                pgconn=conn,
             )
         else:
             raise e.InternalError(f"unexpected poll status: {status}", pgconn=conn)
```
makes things work (no hang).

**Comment by dvarrazzo** [comment] 2023-05-16 08:45
Thank you for checking @dlax 

The connection will go out of scope when the exception does, but I understand it's not timely enough for this. We should check, if we make that change, if there is any regression in the test suite, and it's probably worth adding that test to the test suite too.

**Comment by dlax** [comment] 2023-05-16 08:53
I can work on a proper fix based on my suggestion, including tests, if 
that's okay by you; let me know.

**Comment by dvarrazzo** [comment] 2023-05-16 09:12
@dlax thank you, if you can do that it would be great.

I don't think that Error.pgconn is used anywhere internally, but maybe there is some value in keeping it. How do you see about calling `pgconn.finish()` before raising the exception?

**Comment by dlax** [comment] 2023-05-16 14:09
> How do you see about calling `pgconn.finish()` before raising the exception?

I'm afraid this would break the aforementioned use case. For instance, doing this will break the test introduced in #566 because the finished-`pgconn` cannot be used to invoke `PQconnectionNeedsPassword()` and friends.

**Comment by dlax** [comment] 2023-05-16 16:59
I'm able to work around the hang by closing the description of the socket of the `PGconn`:
```diff
diff --git a/psycopg/psycopg/generators.py b/psycopg/psycopg/generators.py
index 584fe47b..23838c6c 100644
--- a/psycopg/psycopg/generators.py
+++ b/psycopg/psycopg/generators.py
@@ -16,6 +16,7 @@ when the file descriptor is ready.
 # Copyright (C) 2020 The Psycopg Team
 
 import logging
+import socket
 from typing import List, Optional, Union
 
 from . import pq
@@ -73,6 +74,7 @@ def _connect(conninfo: str) -> PQGenConn[PGconn]:
         elif status == POLL_WRITING:
             yield conn.socket, WAIT_W
         elif status == POLL_FAILED:
+            socket.close(conn.socket)
             encoding = conninfo_encoding(conninfo)
             raise e.OperationalError(
                 f"connection failed: {pq.error_message(conn, encoding=encoding)}",
```
and then:
```console
$ env PSYCOPG_IMPL=python python -X dev t.py
startup:  b'\x00\x00\x00\x08\x04\xd2\x16/'
read:  b''
Traceback (most recent call last):
  File "/home/denis/src/psycopg/t.py", line 47, in <module>
    connect(host="127.0.0.1", port=server.port)  # raises OperationalError
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denis/src/psycopg/psycopg/build/__editable__.psycopg-3.2.0.dev1-py3-none-any/psycopg/connection.py", line 728, in connect
    raise ex.with_traceback(None)
psycopg.OperationalError: connection failed: received invalid response to SSL negotiation: g
sys:1: ResourceWarning: unclosed <socket.socket fd=3, family=2, type=1, proto=0, laddr=('127.0.0.1', 55615)>
```

But I'm not quite sure what happens in fact...

**Comment by dlax** [comment] 2023-05-16 17:09
Hmm, https://git.postgresql.org/gitweb/?p=postgresql.git;a=blob;f=src/interfaces/libpq/fe-connect.c;h=c4720927d82fcc49c4191b1a20664b323b5780ae;hb=HEAD#l4200, so maybe that's just the proper thing to do?

**Comment by jchampio** [comment] 2023-05-16 17:23
>I'm able to work around the hang by closing the descriptor of the socket of the PGconn

I think that causes a double-close when the handle is finally `PQfinish`'d, which may trash a recycled file descriptor.

>so maybe [`PQfinish` is] just the proper thing to do?

Yeah, there may be other resources besides the socket tied up in the handle, and it'll be important to release those too. Can `needs_password` and `used_password` be cached before releasing it?

**Comment by dlax** [comment] 2023-05-17 08:18
Yes, you're probably right: "leaking" `PGconn` (by attaching it to raised `Error`) is what's causing the problem you describe. On the other hand, removing this would be a breaking change. Caching `needs_password` and `used_password` might be doable (not sure with Cython), but keeping the `PGconn` around after having called `PGfinish()` still does not look clean to me.

**Comment by dvarrazzo** [comment] 2023-05-17 17:22
I played a bit on the example, and I think it is too over-simplified to state that this is a bug in psycopg.

There are three wrong things going on there:

- the recv() in the server has no timeout
- the thread is not daemon
- the exception crashes the program

So I don't see psycopg hanging here: I see your thread blocking the program from exiting. The program might terminate if:

- `server.daemon` is set to True
- `recv()` has a timeout
- the exception is handled instead of made to bubble to top level (and not because there is a leak, just because the socket closing makes `recv()` return).

```python
try:
    connect(host="127.0.0.1", port=server.port)  # raises OperationalError
except psycopg.Error as ex:
    print(f"error connectiong: {ex}")
```

I don't think that the example you show is sufficient for us to change behaviour, especially if it ends up dropping useful features.

I agree that closing the socket is not a good idea because of the risk of double closing.

I am inclined to close the issue here, unless you have a more concrete case, where a well-behaving system is broken by the socket attached to the exception.

**Comment by jchampio** [comment] 2023-05-18 14:40
> There are three wrong things going on there:

The example is just a minimal reproduction to illustrate the leak.

The original code wraps the `connect` call with a context manager (which the PGconn object then surprisingly escapes). It's based on a test suite for libpq support for OAuth. The exception escapes into a higher level of the test suite, I presume so it can be logged at program exit, but that means I don't get to clean it up.

> So I don't see psycopg hanging here

I'm not claiming it is. My program is hanging on an open socket which should have been closed by psycopg. It's the leaked PGconn that I'm reporting, not the hang.

Throwing a bundle of open resources out of their failed constructor (through any attempted context managers), causing them to remain open until Python gets around to cleaning up the exception, is IMO not correct behavior. Your three suggested changes will work around the _hang_ just fine, but they don't release that socket. (And my OAuth proposal would make the leak worse, because there will be _many_ more resources riding inside that handle.)

> ```py
> try:
>    connect(host="127.0.0.1", port=server.port)  # raises OperationalError
>except psycopg.Error as ex:
>    print(f"error connectiong: {ex}")
> ```

I don't think this code solves the root problem, except maybe with CPython in the simplest cases.

Maybe you're assuming the finalizer is guaranteed to run after the `except` block is exited? That's not necessarily true; try for example with `pypy3.9`. Or with CPython, add another layer during exception handling to accidentally create [a reference cycle against the stack:](https://docs.python.org/3/reference/datamodel.html#object.__del__)

```py
def do_connect():
    try:
        connect(host="127.0.0.1", port=server.port)  # raises OperationalError
    except Exception as ex:
        # do something with it temporarily, then re-raise for the top level
        localvar = ex
        raise

try:
    do_connect()
except psycopg.Error as ex:
    print(f"error connecting: {ex}")
    
# still hangs
```

With the current setup, it seems like the only way to guarantee correct cleanup is to make sure that every single `Error` is accounted for and any `PGconn` inside explicitly `finish`'d. I think that's surprising at a minimum, and I suspect that many people will simply not do it.

**Comment by dlax** [comment] 2023-05-19 07:43
One solution would be to introduce a new implementation of the `PGconn` *protocol*, that would capture the state of the real `PGconn` before it gets finished in `generators.connect()`, and attach it to the `OperationError` there.

Here's how it would look like:
```diff
diff --git a/psycopg/psycopg/errors.py b/psycopg/psycopg/errors.py
index d8b7f6fd..5c52c018 100644
--- a/psycopg/psycopg/errors.py
+++ b/psycopg/psycopg/errors.py
@@ -31,6 +32,28 @@ ErrorInfo: TypeAlias = Union[None, PGresult, Dict[int, Optional[bytes]]]
 _sqlcodes: Dict[str, "Type[Error]"] = {}
 
 
+@dataclass
+class _PGconn:
+    needs_password: bool
+    used_password: bool
+    # ... To be completed with other properties from PGconn.,
+
+    @property
+    def pgconn_ptr(self) -> None:
+        return None
+
+    @classmethod
+    def connect(cls, conninfo: bytes) -> NoReturn:
+        raise OperationalError("the connection is closed")
+
+    # ... To be completed for other methods of PGconn.
+
+
+def _err_pgconn(pgconn: PGconn) -> _PGconn:
+    args = {f.name: getattr(pgconn, f.name) for f in fields(_PGconn)}
+    return _PGconn(**args)
+
+
 class Warning(Exception):
     """
     Exception raised for important warnings.
diff --git a/psycopg/psycopg/generators.py b/psycopg/psycopg/generators.py
index 584fe47b..74565766 100644
--- a/psycopg/psycopg/generators.py
+++ b/psycopg/psycopg/generators.py
@@ -74,11 +74,12 @@ def _connect(conninfo: str) -> PQGenConn[PGconn]:
             yield conn.socket, WAIT_W
         elif status == POLL_FAILED:
             encoding = conninfo_encoding(conninfo)
-            raise e.OperationalError(
-                f"connection failed: {pq.error_message(conn, encoding=encoding)}",
-                pgconn=conn,
-            )
+            msg = pq.error_message(conn, encoding=encoding)
+            econn = e._err_pgconn(conn)
+            conn.finish()
+            raise e.OperationalError(f"connection failed: {msg}", pgconn=econn)
         else:
+            # TODO conn.finish() etc.
             raise e.InternalError(f"unexpected poll status: {status}", pgconn=conn)
 
     conn.nonblocking = 1
```

I would say this will not be a breaking change because the interface of `PGconn` is respected. It could even be considered as an improvement because the new error-specific `PGconn` would be implemented so as to constantly raise `OperationalError` upon all operations.

What do you think?

**Comment by dlax** [comment] 2023-05-19 10:43
> this is not a bad idea

Thanks; I'll try to send a PR later today (probably based on #566).

**Closed** 2023-06-13 12:12 UTC
