### ISSUE TITLE
Change repository structure to avoid directory/module name conflicts

### ISSUE THREAD

**Issue by bluetech** [psycopg/psycopg#494] opened 2023-01-24 23:12 UTC
When following the Hacking instructions in the README, the pytest step fails for me with various import errors. The problem is that `import psycopg` in the tests ends up importing the `psycopg` directory at the top-level of the repository as an empty namespace package, instead of the editable-installed one from the venv. I tried various tricks (isolated mode, pytest import modes, running from another directory) but it seems pytest is very insistent on picking the top-level directory first. It might be something on my side, but I don't think so.

To avoid this confusion I propose changing the directory layout. Instead of this:

```
.
├── psycopg
│   ├── LICENSE.txt
│   ├── psycopg
│   ├── pyproject.toml
│   ├── README.rst
│   ├── setup.cfg
│   └── setup.py
├── psycopg_c
│   ├── build_backend
│   ├── LICENSE.txt
│   ├── MANIFEST.in
│   ├── psycopg_c
│   ├── pyproject.toml
│   ├── README-binary.rst
│   ├── README.rst
│   ├── setup.cfg
│   └── setup.py
├── psycopg_pool
│   ├── LICENSE.txt
│   ├── psycopg_pool
│   ├── pyproject.toml
│   ├── README.rst
│   ├── setup.cfg
│   └── setup.py
├── pyproject.toml
```

Change to this:

```
.
├── pyproject.toml
├── src
│   ├── psycopg
│   │   ├── LICENSE.txt
│   │   ├── psycopg
│   │   ├── pyproject.toml
│   │   ├── README.rst
│   │   ├── setup.cfg
│   │   └── setup.py
│   ├── psycopg_c
│   │   ├── build_backend
│   │   ├── LICENSE.txt
│   │   ├── MANIFEST.in
│   │   ├── psycopg_c
│   │   ├── pyproject.toml
│   │   ├── README-binary.rst
│   │   ├── README.rst
│   │   ├── setup.cfg
│   │   └── setup.py
│   └── psycopg_pool
│       ├── LICENSE.txt
│       ├── psycopg_pool
│       ├── pyproject.toml
│       ├── README.rst
│       ├── setup.cfg
│       └── setup.py

```

Even though it doesn't strictly follow the [src layout](https://packaging.python.org/en/latest/discussions/src-layout-vs-flat-layout/) recommendation, it will fix the problem.

**Comment by dvarrazzo** [comment] 2023-01-24 23:29
I don't have this problem. Can you try `pip install --config-settings editable_mode=strict -e "./psycopg[dev,test]"` please?

**Comment by asqui** [comment] 2023-01-25 06:26
Interesting observation… I’m not familiar with this specific problem but one question I thought worth asking is why are you the first person to encounter this? What is different about the way that Daniele and other contributors, and CI, run the tests?

**Comment by dvarrazzo** [comment] 2023-01-25 07:21
pip -e broke some time ago, see https://github.com/pypa/setuptools/issues/3557

When the project started, a pip -e was working as expected. Now I'm reluctant to move all the files in the project and make git history more complex to follow. The issue is still open in PyPA field, so I have some hope that it might be fixed.

The issue is mentioned in the readme, so I think we can close this: with the documented workaround, editable mode works.

**Closed by dvarrazzo** 2023-01-25 07:21 UTC

**Comment by dvarrazzo** [comment] 2023-01-25 07:38
@asqui in the ci I had to remove all the `-e`. Without it, install and import work well, and the ci runner are deleted after a run anyway

**Comment by dlax** [comment] 2023-01-25 08:34
I never had such a problem either... but I however find the current layout a bit awkward to work with on a regular basis. Typically, `vim psycopg/psycopg/connection.py` is a bit strange. (No worries, it's far from being a big deal, I'm used to it.)

Yet, the layout suggested above seems even more convoluted  because it's close to the so-called src-layout but it's not it since the nested structure would remain. Now it'd be `vim src/psycopg/psycopg/connection.py`, which is ... ugh.

Alternatively, we could just rename top-level directories to avoid conflicts with package names:
```.
├── c
│   ├── build_backend
│   ├── LICENSE.txt
│   ├── MANIFEST.in
│   ├── psycopg_c
│   ├── pyproject.toml
│   ├── README-binary.rst
│   ├── README.rst
│   ├── setup.cfg
│   └── setup.py
├── pool
│   ├── LICENSE.txt
│   ├── psycopg_pool
│   ├── pyproject.toml
│   ├── README.rst
│   ├── setup.cfg
│   └── setup.py
├── py
│   ├── LICENSE.txt
│   ├── psycopg
│   ├── pyproject.toml
│   ├── README.rst
│   ├── setup.cfg
│   └── setup.py
├── pyproject.toml
├── README.rst
└── tests
    ...
```
