### ISSUE TITLE
The refactor of conninfo.py broke the service parameter.

### ISSUE THREAD

**Issue by xbarra** [psycopg/psycopg#694] opened 2023-12-05 14:48 UTC
Since we updated from psycopg-3.1.8 to psycopg-3.1.[13,14] we are unable to connect by passing the service parameter in the conninfo.

Since we rely on the connection parameters present in the pgservicefile, we don't provide host, port or anything, just the service.

According to psycopg documentation, (since it points to the postgres documentation) should be an accepted method. 

Could we get the support of the service parameter back?

Best regards.

**Comment by dvarrazzo** [comment] 2023-12-06 11:30
Ouch, this might need that we will need to parse the pg_service file... :sob: 

Looking into it to assess the problem.

**Comment by xbarra** [comment] 2023-12-06 11:38
> Ouch, this might need that we will need to parse the pg_service file... 😭
> 
> Looking into it to assess the problem.

I had to do that parsing when trying to use other libraries and was not fun.

Personally, I would treat the case I get a service file as a different case where I don't know a port and host until I am connected. But I haven't read the reasons to always specify the port. 

Let me know if you need extra information regarding the issue or testing.

Thanks for your time.

**Comment by dpprdan** [comment] 2023-12-06 14:47
> Ouch, this might need that we will need to parse the pg_service file...

Really? It worked fine with psycopg <= 3.1.12 and pg_service file is [built into libpq](https://www.postgresql.org/docs/current/libpq-pgservice.html) AFAICT.

(Somewhat) reproducible example:

With this `.pg_service` file (password set in [`pgpass.conf`](https://www.postgresql.org/docs/current/libpq-pgpass.html) or env var)

```ini
# https://www.postgresql.org/docs/current/libpq-pgservice.html

[mydb]
host=myhost
dbname=postgres
user=postgres
```

and (run in a `mcr.microsoft.com/devcontainers/python:1-3.11-bookworm` devcontainer)

```python
import psycopg
Connection.connect("postgresql://?service=mydb")
```

I get 

```python
---------------------------------------------------------------------------
OperationalError                          Traceback (most recent call last)
Cell In[10], [line 2](vscode-notebook-cell:?execution_count=10&line=2)
      [1](vscode-notebook-cell:?execution_count=10&line=1) import psycopg
----> [2](vscode-notebook-cell:?execution_count=10&line=2) Connection.connect("postgresql://?service=mydb")

File ~/.local/lib/python3.11/site-packages/psycopg/connection.py:745, in Connection.connect(cls, conninfo, autocommit, prepare_threshold, row_factory, cursor_factory, context, **kwargs)
    [743](file:///home/vscode/.local/lib/python3.11/site-packages/psycopg/connection.py?line=742) if not rv:
    [744](file:///home/vscode/.local/lib/python3.11/site-packages/psycopg/connection.py?line=743)     assert last_ex
--> [745](file:///home/vscode/.local/lib/python3.11/site-packages/psycopg/connection.py?line=744)     raise last_ex.with_traceback(None)
    [747](file:///home/vscode/.local/lib/python3.11/site-packages/psycopg/connection.py?line=746) rv._autocommit = bool(autocommit)
    [748](file:///home/vscode/.local/lib/python3.11/site-packages/psycopg/connection.py?line=747) if row_factory:

OperationalError: connection is bad: No such file or directory
	Is the server running locally and accepting connections on that socket?
```

```python
psycopg.__version__
# '3.1.14'
```

As said, the above works fine with psycopg <= 3.1.12

The regression might be due to https://github.com/psycopg/psycopg/issues/674?

**Comment by dvarrazzo** [comment] 2023-12-06 15:07
We need to check if the libpq supports the pg_service file in async mode (i.e. when connecting via [`PQconnectStart`](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-PQCONNECTSTARTPARAMS) rather than [`PQconnectdb`](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-PQCONNECTDB).

A few features are not supported in async mode: timeout is not supported and, as a consequence, connection retries (#674) and `load_balance_hosts`.

Note: we use async libpq connection in both sync and async psycopg cursors. But, in async psycopg cursors we also do further manipulation, by querying the DNS using async functions and populate the connection string `hostaddr` to avoid a libpq blocking call (see #259).

So, before looking at the code, the thing that I see happening is that, even if we can adjust something simple to avoid `service` to break, if the service is configured with multiple hosts, it will manifest the same problem of #674, and, if connecting with an async connection, it will block on DNS resolution as per #259.

**Comment by vacarme** [comment] 2023-12-06 16:49
Don't know yet if related, but > 3.1.12 does break the [Gitlab Postgres Service](https://docs.gitlab.com/ee/ci/services/postgres.html), which is not able to established connection whereas locally there is no issue.

**Comment by dvarrazzo** [comment] 2023-12-06 17:09
@vacarme that's bad to hear. Could you please give more details? What is the connection string that used to work on 3.1.12 and broke afterwards? What is the error?

**Comment by dvarrazzo** [comment] 2023-12-07 11:13
I think I will operate this way:

First part: we will fix the "connection attempts" algorithm to avoid touching anything unless it detects that multiple hosts have been really specified. At the moment it takes the freedom of replacing the unspecified parameters with values taken from their defaults or env vars, and this breaks an eventual pg_service specification.

This should result in fixing the regression introduced in 3.1.13, but will not allow to specify multiple hosts in the pg_service file, and would block on DNS resolution if the host is taken from the services file in an async connection. These problems are not regressions, they were present before 3.1.13 too.

This would be released in psycopg 3.1.15.

Second part: we will introduce pg_service parsing (which seems easy to parse using the [stdlib `configparser`](https://docs.python.org/3/library/configparser.html)) and we will consider the definitions included there to solve the problem mentioned above.

This be probably released in a following psycopg 3.1.x release.

**Comment by xbarra** [comment] 2023-12-07 11:30
> Second part: we will introduce pg_service parsing (which seems easy to parse using the [stdlib `configparser`](https://docs.python.org/3/library/configparser.html)) and we will consider the definitions included there to solve the problem mentioned above.

That's what I used when I had to parse it:
````
    config = configparser.ConfigParser()
    config.read(os.getenv('PGSERVICEFILE'))
    pgparams = {k:v for k,v in config['main'].items()}
```

**Comment by dvarrazzo** [comment] 2023-12-07 13:08
@vacarme this seems a somewhat unrelated issue we can look into separately. Thank you for the info. Opened #695 to address it. I will add some details there; please let's move there this conversation.

**Comment by dvarrazzo** [comment] 2023-12-14 03:26
Fixed by #700

**Closed by dvarrazzo** 2023-12-14 03:26 UTC

**Comment by dvarrazzo** [comment] 2023-12-14 13:02
Psycopg 3.1.15 being released, which should fix this issue. Please try it out and let us know how it goes, thank you!

**Comment by dpprdan** [comment] 2023-12-14 15:22
Works on my machine 🎉

**Comment by xbarra** [comment] 2023-12-14 15:37
Here too. Thank you so much 🥳

**Comment by dvarrazzo** [comment] 2023-12-14 16:59
Thank you @dpprdan, @xbarra, your testing is very appreciated :)

Please know that, in my understanding, values in the service file are not yet treated as carefully as if specified in a connection string or an env var, see #698, #699. I will address those issues too, but un-breaking `service` was more important.

**Comment by xbarra** [comment] 2023-12-15 08:09
> Thank you @dpprdan, @xbarra, your testing is very appreciated :)
> 
> Please know that, in my understanding, values in the service file are not yet treated as carefully as if specified in a connection string or an env var, see #698, #699. I will address those issues too, but un-breaking `service` was more important.

We really appreciate having service working. Thank you very much
